package edu.asu.diging.gilesecosystem.requests;

public interface IStorageRequest extends IRequest {

    public abstract void setFileType(FileType fileType);

    public abstract FileType getFileType();

    public abstract void setUsername(String username);

    public abstract String getUsername();

    public abstract void setUploadDate(String uploadDate);

    public abstract String getUploadDate();

    public abstract void setFilename(String filename);

    public abstract String getFilename();

    /**
    * Returns the service the file is generated by.
    * @return the service the file is generated by.
    */
    public abstract String getGeneratedByService();
    
    /**
    * Sets the value of the service the file is generated by.
    * @param generatedByService the service that generated the file.
    */
    public abstract void setGeneratedByService(String generatedByService);
}
